### ISSUE TITLE
Choosing the software license for the main repository

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2022-2023#13]
Hi @open-sci/pika-py and @open-sci/playarists,

As anticipated in [one of the past lectures](https://docs.google.com/presentation/d/1LHPGt18AhFF-VkzQljlsiADWCnWvzy-I6ZoMDNtJMqo/edit#slide=id.gcd92ad6878_0_33), we have to specify the license for all the software available in our [main repository](https://github.com/open-sci/2022-2023/). My preference would be to use the [ISC license](https://opensource.org/licenses/ISC) but I am happy to use another one if you think it is more appropriate for our course.

What do you think? Please start a discussion as comments on this issue.

**Comment by olgagolgan** [comment]
I agree with you on the ISC license, since it grants permission to use, copy, modify the code for any purpose.

**Comment by ghasempouri1984** [comment]
I understand that the ISC license allows new developers to change the license, which can be a concern, especially when different parties involved in a project have unequal access to resources, such as technical support and supervision or unequal financial supports, for further development. To my point of view, this inequality might lead to imbalances in control over the OpenScience projects and their licensing in general. However, **I agree with using the ISC license for our main repository for this course** because I am aware of Prof. Peroni's and colleagues' points of view that it promotes fluidity in the context of our course. This license is simple, permissive, and encourages collaboration, which aligns with the goals of our course.

**Comment by MaddaGh** [comment]
In general, **I also have no strong opinions against using ISC Licence** for this software, although I do have some reflections to share:

I really like the fact that [GNU General Public License](https://opensource.org/license/gpl-3-0/) gives many clear specifications and practical examples, as I find it more user-friendly and I believe it can give authors much more security (considering some of the fears people may have in sharing openly their work. For ex. this license expects you to track the modifications you may have made)

> For the developers’ and authors’ protection, the GPL clearly explains that there is no warranty for this free software. For both users’ and authors’ sake, the GPL requires that modified versions be marked as changed, so that their problems will not be attributed erroneously to authors of previous versions.

Whereas, I find ISC a bit vague in its application cases. 
On this point it's worth noting that [MIT License](https://opensource.org/license/mit/), that I saw was adopted last year, is not much different from ISC but also states "without warranty of any kind, expressed or implied" and mentions "noninfringement". 

Finally, I agree with the copyleft clause especially with how GNU GPL describes it. But I realize this is mainly because I can hardly think of "ethical" scenarios where it could be necessary to make a software non-free in order to use it, hence the copyleft clause could be an impediment for people to reuse it (such as it could be in the case of handling sensitive data and needing to privatize them). 
As far as I understood this would not come down to marketization, because GNU GPL does not prevent charging fees for reusage, as long as the software stays open source. 
So what could be a scenario that doesn't involve "unethical" purposes, where a copyleft clause is actually a reusability impediment?

**Comment by ghasempouri1984** [comment]
> So what could be a scenario that doesn't involve "unethical" purposes, where a copyleft clause is actually a reusability impediment?

- Companies or developers may have a proprietary software that they want to integrate with open-source software. They might not be able to open-source their proprietary code **due to intellectual property or trade secret concerns**. In this case, using a copyleft licensed open-source software like GPL could be an impediment.

- There could be cases where developers are working with multiple open-source projects that use different licenses. Some licenses might not be compatible with the copyleft license of the open-source software.

**In these scenarios, using a permissive license like ISC or MIT could be more appropriate.**

While I agree with using ISC or MIT licenses in the context of our work and many other openscience projects, in my opinion the GPL works as **"pure openscience"** context, where each parties involved (or will be involved) work in opensciene for openscience.

**Comment by ghasempouri1984** [comment]
I think we all agree  on ISC, and we can close the issue.
