### ISSUE TITLE
Revision of material - team Playarists

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2022-2023#29]
Dear @open-sci/playarists,

Please find here attached my comments on all your material. You have to address all of them and, once finalised, close this issue with a comment containing your reply to each of the points I have highlighted. There is no specific deadline to complete this task; thus, please take your time.

Please, be aware that some modifications in some documents may also affect modifications in other documents. As a final note, please remember to keep your notebooks up-to-date.

After closing this issue, please remember to update your material.md file by specifying the references to the new version of all your documents.

As usual, for further doubts, do not hesitate to contact me in the Slack channel or just comment on this issue here.

# General comments from the presentation

The following comments and questions should be addressed and may also result in the modification of some of the material prepared for the project:

* Did you have the chance to compare the US vs Europe, also in terms of the kinds of articles?

* You said that, considering the countries of journals, the UK wins. How mega-journals (i.e. journals that handle a lot of different disciplines) may affect this result? Is that the case in your data?

* It would be interesting to compare at least with Colavizza et al. (2022) to look at the coverage of digital humanities in OpenCitations Meta, mixing the data from that article with those you obtained.

* How would you solve the lacking of information in ERIH-PLUS? Can you suggest a possible strategy to address it? 

# DMP

The document (PDF) of the DMP says "Version 0" but in the metadata, it is "Version 3". Please correct.

Why did you use the Horizon 2020 template instead of the Horizon Europe one?

## Title: SSH_OA_Publications_in_OCMeta

- 1.1.3 What are the formats of the described generated/collected data? Did you use any plain text (TXT), HTML, XML, PDF/A in your data? Did you also use JSON?

- 2.1.1 Are you re-using the described data and how? I did not understand what you said here. Can you please rephrase?

- 3.1.1.3 Will your metadata use standardised vocabularies? You answered yes, but before you replied, you did not use metadata. What is the true thing?

- 3.1.1.5 Will you make the metadata available free-of-charge? Where? I did not see any RDF serialisation format anywhere, honestly.

- 3.1.1.9 Will you provide clear version numbers for your data? You said so, but then you are not doing it (e.g. you used Version 1 etc. instead of Version 1.0.0).

- 3.1.1.15 Will you use standardised formats for the described data? Did you also use JSON?

- 3.1.2.3 How will the data be made available? What is the project website? Please specify it.

- 3.1.4.4 What internationally recognised licence(s) will you use for the
described data? But it seems that the data have been published with CC-BY...

- 3.1.4.7 Describe the data quality assurance processes. Which formats? Which data models and standards?

## Title: Data management software

Some of the points arisen below apply also here. In addition:

1.1.3 What are the formats of the described generated/collected data? "Software" is not a format.

3.1.1.22 Will you provide metadata describing the quality of the data? It is not clear how you have used it. Do you have a report about it somewhere? The link to the report should be added to the DMP.

3.1.2.3 How will the data be made available? What is "Repository of Archive"?

3.1.4.7 Describe the data quality assurance processes. You should be a bit more precise here. It is not clear how you will do it.

3.1.4.8 Will you provide any support for data reuse? Where is the link to the notebook?

# Protocol

There are a lot of references to classes and methods in Python that, while fine to use, do not help the understanding of the protocol. While excerpts of code can be used in the definition of the protocol, it is important to explain them and, in particular, all the passages. Please, update the protocol so that a reader reading it can understand how to run the experiment without looking necessarily to external material. Explain the procedures to follow, and limit the links to the code where necessary.

# Software

The section "Naming convention of Datasets" in the README of the software seems lacking of some information. Can you please update it?

# Data

The description of the data on Zenodo should also detail the format used for data (column names, their meaning, etc.).

# Article

There are no authors specified! Please add all of them, with appropriate affiliations.

Abstract: please use the same structured abstract already developed in the paper. The Abstract section is usually not numbered.

Introduction: it should include at least the research questions, and it should also contain, at the very end, how the rest of the paper is actually structured (e.g. "The rest of the paper is structured as follows. In Section 2, ...").

Materials and Methods: Remove my name as an author of your software - you did it, not me. Cite properly the data you have reused (Meta, COCI, etc.) by creating appropriate bibliographic references for them (pointing to the right version, e.g., on Figshare). Saying "we downloaded Meta" and then adding the link to opencitations.net/meta is not correct.

Results: The figures should have a proper caption describing the graph. This should be true for **all** figures in the whole text.

Discussion: Please identify a subsection here where to list all the limitations properly.

Conclusions: they are missing and should also contain some sketches of future works.

References: if you use the references (I agree), please cite them properly in the text **without** using footnotes, but using APA style.

**Comment by ghasempouri1984** [comment]
**General comments from the presentation**

**Did you have the chance to compare the US vs Europe, also in terms of the kinds of articles?**
While we had noticed it we did not accomplished to prepare the results for the presentation.

**You said that, considering the countries of journals, the UK wins. How mega-journals (i.e. journals that handle a lot of different disciplines) may affect this result? Is that the case in your data?**
Regarding the impact of mega-journals on the results, the article does not directly address this. It does mention that a higher coverage of journals does not necessarily imply a larger coverage of publications, since the quantity of articles published by a journal may differ significantly

**It would be interesting to compare at least with Colavizza et al. (2022) to look at the coverage of digital humanities in OpenCitations Meta, mixing the data from that article with those you obtained.**
Yes for sure it will be considered for near future update of the article.

**How would you solve the lacking of information in ERIH-PLUS? Can you suggest a possible strategy to address it?**
ERIH-PLUS could collaborate with other bibliographic databases to fill in the gaps in their data through linking records between databases to provide more comprehensive information. In addition, researchers and institutions can contribute missing information. 

**DMP**
**The document (PDF) of the DMP says "Version 0" but in the metadata, it is "Version 3". Please correct.**
It is fixed.

**Why did you use the Horizon 2020 template instead of the Horizon Europe one?**
There were some issues regarding adopting it through its website. 

**Title: SSH_OA_Publications_in_OCMeta**
**1.1.3 What are the formats of the described generated/collected data? Did you use any plain text (TXT), HTML, XML, PDF/A in your data? Did you also use JSON?**
we clarified this issue(CSV and JSON).

**2.1.1 Are you re-using the described data and how? I did not understand what you said here. Can you please rephrase?**
No, we dont.

**3.1.1.3 Will your metadata use standardised vocabularies? You answered yes, but before you replied, you did not use metadata. What is the true thing?**
We corrected this issue. Our answer is 'No'. The data we used for this study came from secondary sources such as the OpenCitations Meta database, the ERIH-PLUS bibliographic index, and the DOAJ index. These data sources already implement standardised vocabularies in their metadata structures. However, our task primarily involved the analysis and interpretation of these pre-existing data, not the creation of new metadata. Therefore, our interaction with standardised vocabularies was minimal.

**3.1.1.5 Will you make the metadata available free-of-charge? Where? I did not see any RDF serialisation format anywhere, honestly.**
Yes. we clarified this issue.  It is not RDF serialisation. The metadata will be available on Zenodo.

**3.1.1.9 Will you provide clear version numbers for your data? You said so, but then you are not doing it (e.g. you used Version 1 etc. instead of Version 1.0.0).**
Yes we clarified the issue.

**3.1.1.15 Will you use standardised formats for the described data? Did you also use JSON?**
Yes, We clarified this issue.

**3.1.2.3 How will the data be made available? What is the project website? Please specify it.**
We have clarified this issue. On Zenodo.

**3.1.4.4 What internationally recognised licence(s) will you use for the
described data? But it seems that the data have been published with CC-BY...**
We have clarified this issue.

**3.1.4.7 Describe the data quality assurance processes. Which formats? Which data models and standards?**

This part has been removed. The primary focus of our research was to analyze the data available from established secondary sources including the OpenCitations Meta database, the ERIH-PLUS bibliographic index, and the DOAJ index. These sources are trusted and widely-used in academic research, and they employ their own stringent data quality assurance processes to ensure the reliability and validity of their data. As such, we did not find it necessary to apply additional data quality assurance processes.

However, we are aware that it's essential to note that data quality assurance processes aren't just about ensuring the data we are using, but also about ensuring that the processes and methods we use to analyze that data are robust and reliable.

During processing and analyzing the data, we did some tests, but because of lack of data in QA process we did not use specific methodologies.

**Title: Data management software**

**1.1.3 What are the formats of the described generated/collected data? "Software" is not a format.**
We corrected this issue.

**3.1.1.22 Will you provide metadata describing the quality of the data? It is not clear how you have used it. Do you have a report about it somewhere? The link to the report should be added to the DMP.**
No we do not provide it. We corrected this issue.

**3.1.2.3 How will the data be made available? What is "Repository of Archive"?**
On GitHub and Zenodo. Repository of archive was an option on the website we were working on DMP. We corrected this issue.

**3.1.4.7 Describe the data quality assurance processes. You should be a bit more precise here. It is not clear how you will do it.**

What we did were for example checking for missing values, duplicate entries, or before initiating the analysis, we ensured that our data conforms to the specified format. This means checking that the data structure is correct, fields are in the appropriate format, and the data is standardized and ready for analysis.

While we created tests scripts and also used partial of the Data for specific tests, we did not use specific methodologies as professionals in software dev field.

**3.1.4.8 Will you provide any support for data reuse? Where is the link to the notebook?**
We clarified this issue. By usage guidelines in the github repository of project.

**# Protocol**

**There are a lot of references to classes and methods in Python that, while fine to use, do not help the understanding of the protocol. While excerpts of code can be used in the definition of the protocol, it is important to explain them and, in particular, all the passages. Please, update the protocol so that a reader reading it can understand how to run the experiment without looking necessarily to external material. Explain the procedures to follow, and limit the links to the code where necessary.**
We clarified the Protocols by removing many references in this section "Retrieving Data about Countries and Disciplines".


**Software**
The section "Naming convention of Datasets" in the README of the software seems lacking of some information. Can you please update it?
Naming convention in the README of the software on Github repository became updated.

**Data**
The description of the data on Zenodo should also detail the format used for data (column names, their meaning, etc.).
The description of data on Zenodo updated.

**Article**
**There are no authors specified! Please add all of them, with appropriate affiliations.**
Authors with affiliations added.

**Abstract: please use the same structured abstract already developed in the paper. The Abstract section is usually not numbered.**
we used structured abstract and abstract is not numbered.

**Introduction: it should include at least the research questions, and it should also contain, at the very end, how the rest of the paper is actually structured (e.g. "The rest of the paper is structured as follows. In Section 2, ...").**
introduction already contained research questions. now it is specified with RQ1, ...etc. 

**Materials and Methods: Remove my name as an author of your software - you did it, not me. Cite properly the data you have reused (Meta, COCI, etc.) by creating appropriate bibliographic references for them (pointing to the right version, e.g., on Figshare). Saying "we downloaded Meta" and then adding the link to opencitations.net/meta is not correct.**
Your name has been removed. The citation of reused data fixed.

**Results: The figures should have a proper caption describing the graph. This should be true for all figures in the whole text.**
Every figures now has a caption and is numbered.

**Discussion: Please identify a subsection here where to list all the limitations properly.**
We added limitations subsection.

**Conclusions: they are missing and should also contain some sketches of future works.**
Conclusion is added with mentioning of future works.

**References: if you use the references (I agree), please cite them properly in the text without using footnotes, but using APA style.**
Footnotes removed. And references at the end is in APA style. To finding APA format for each article , it is searched with Google Scholar and by the'cite' option the APA format retrieved.

**Comment by MaddaGh** [comment]
**General comments from the presentation**
**Did you have the chance to compare the US vs Europe, also in terms of the kinds of articles?**

Yes we did, please refer to the research article to find our comparison (section 3.3.1.Publications, https://doi.org/10.5281/zenodo.8263908)

**You said that, considering the countries of journals, the UK wins. How mega-journals (i.e. journals that handle a lot of different disciplines) may affect this result? Is that the case in your data?**

The countries' distribution in terms of number of publications is not particularly affected, since there is only one mega-journal (MJ) published by the UK (Nature, issn:0028-0836) and when running the data excluding MJ we found no changes in the rank. In fact, if we look at the journals with more publications, excluding MJ and United States, we find a other countries presence at the top, such as the Netherlands at the first place (Brain Research, issn:1872-6240), Switzerland at the third (International Journal of Environmental Research and Public Health, issn:1660-4601, erih:472952).
On the other hand, we found that mega-journals, were affecting the publications' distritbution over disciplines.
We added to the software a functionality to compute the results without MJ for providing a better understanding of the data. The results are reported in the research article. Please refer to the Results' section of the article to have a better insight. (https://doi.org/10.5281/zenodo.8263908)

**It would be interesting to compare at least with Colavizza et al. (2022) to look at the coverage of digital humanities in OpenCitations Meta, mixing the data from that article with those you obtained.**

Although we didn't have the time to do so ourselves, we added such suggestion in the Conclusions section of the article

**How would you solve the lacking of information in ERIH-PLUS? Can you suggest a possible strategy to address it?**

It is worth mentioning that ERIH provides a system, facilitated by Dimensions, to search and download publications’ data in batches of 500 publications at time and that single disciplines are, in fact, assigned to every publication in the index. Nonetheless, it is impossible to access these information in an easy way, both for structure of data and time consumed. To this regard, one could try to contact the ERIH administration directly to see if its possible to obtain such data, or if they are envisioning an update on their website to allow access to publications data.
Another possibility is to access granular data about disciplines by incorporating resources coming from proprietary database like Dimensions, that also contain research area metadata.

**DMP**
**The document (PDF) of the DMP says "Version 0" but in the metadata, it is "Version 3". Please correct.**
It is fixed.

**Why did you use the Horizon 2020 template instead of the Horizon Europe one?**

At the time the DMP was created, we did not know that Horizon 2020 is terminated and now substituted by Horizon Europe. While trying to understand what template to use, we found more examples were adopting Horizon 2020, as well as easily accessible guidelines, so we thought it might be useful to use the same template. 
After assessing the difference between the two, we couldn't find significant discrepancies if not for the formulations of the concepts. For this reason, we have decided to keep Horizon 2020.

**Title: SSH_OA_Publications_in_OCMeta**
**1.1.3 What are the formats of the described generated/collected data? Did you use any plain text (TXT), HTML, XML, PDF/A in your data? Did you also use JSON?**
we clarified this issue(CSV and JSON).

**2.1.1 Are you re-using the described data and how? I did not understand what you said here. Can you please rephrase?**
No, we dont.

**3.1.1.3 Will your metadata use standardised vocabularies? You answered yes, but before you replied, you did not use metadata. What is the true thing?**
We corrected this issue. Our answer is 'No'.

**3.1.1.5 Will you make the metadata available free-of-charge? Where? I did not see any RDF serialisation format anywhere, honestly.**
Yes. we clarified this issue. It is not RDF serialisation. The metadata will be available on Zenodo.

**3.1.1.9 Will you provide clear version numbers for your data? You said so, but then you are not doing it (e.g. you used Version 1 etc. instead of Version 1.0.0).**
We are providing clear versioning for our data.
Software is published in v.1.0.0 (https://doi.org/10.5281/zenodo.7979757) and in v. 1.1.0 (https://doi.org/10.5281/zenodo.8253819). We have decided to version the second release as a minor update, since the new code does not alter the previous version but only add new functionalities.
Data are published in
- v.1.0.0 (https://doi.org/10.5281/zenodo.7979592) it's the first published results dataset
- v.1.1.0 (https://doi.org/10.5281/zenodo.8250858) it's one of the two result datasets published running the new version of the software. This dataset includes mega-journals. We considered this a minor update because in the common csv files there are no changes, but in v.1.1.0 new files are added
- v.2.0.0 (https://doi.org/10.5281/zenodo.8249907) it's one of the two result datasets published running the new version of the software. This dataset excludes mega-journals, for this reason csv files in common with the previous version of the dataset are different. Moreover, new files are added

**3.1.1.15 Will you use standardised formats for the described data? Did you also use JSON?**
Yes, We clarified this issue in the DMP, we also used JSON.

**3.1.2.3 How will the data be made available? What is the project website? Please specify it.**
On GitHub and Zenodo. Repository of archive was an option on the website we were working on DMP. We corrected this issue.

**3.1.4.4 What internationally recognised licence(s) will you use for the
described data? But it seems that the data have been published with CC-BY...**
We have clarified this issue. We have used Creative Commons Attribution 1.0 Generic (CC BY 1.0)

**3.1.4.7 Describe the data quality assurance processes. Which formats? Which data models and standards?**
What we did were for example checking for missing values, duplicate entries, or before initiating the analysis, we ensured that our data conforms to the specified format. This means checking that the data structure is correct, fields are in the appropriate format, and the data is standardized and ready for analysis.

While we created tests scripts and also used partial of the Data for specific tests, we did not use specific methodologies as professionals in software dev field.

**Title: Data management software**
**Some of the points arisen below apply also here. In addition:**

**1.1.3 What are the formats of the described generated/collected data? "Software" is not a format.**
We corrected this issue.

**3.1.1.22 Will you provide metadata describing the quality of the data? It is not clear how you have used it. Do you have a report about it somewhere? The link to the report should be added to the DMP.**
No we do not provide it. We corrected this issue.

**3.1.2.3 How will the data be made available? What is "Repository of Archive"?**
On GitHub and Zenodo. Repository of archive was an option on the website we were working on DMP. We corrected this issue.

**3.1.4.7 Describe the data quality assurance processes. You should be a bit more precise here. It is not clear how you will do it.**
What we did were for example checking for missing values, duplicate entries, or before initiating the analysis, we ensured that our data conforms to the specified format. This means checking that the data structure is correct, fields are in the appropriate format, and the data is standardized and ready for analysis.

While we created tests scripts and also used partial of the Data for specific tests, we did not use specific methodologies as professionals in software dev field.

**3.1.4.8 Will you provide any support for data reuse? Where is the link to the notebook?**
We clarified this issue. By usage guidelines in the github repository of project.

**Protocol**

**There are a lot of references to classes and methods in Python that, while fine to use, do not help the understanding of the protocol. While excerpts of code can be used in the definition of the protocol, it is important to explain them and, in particular, all the passages. Please, update the protocol so that a reader reading it can understand how to run the experiment without looking necessarily to external material. Explain the procedures to follow, and limit the links to the code where necessary.**
We have revised the protocol to be more clear and explain all the passages in the code. Where we left some functions' names or other specific naming in the code, it is done for sake of clarity since the workflow is complex and we thought that referring in an abstract way to some parts of it could be even more confusing for the reader. 
Please refer to the new version of the protocol (https://dx.doi.org/10.17504/protocols.io.5jyl8jo1rg2w/v5).

**Software
The section "Naming convention of Datasets" in the README of the software seems lacking of some information. Can you please update it?**
The section has been updated

**Data
The description of the data on Zenodo should also detail the format used for data (column names, their meaning, etc.).**
The new data published on zenodo are described in detail:
- https://doi.org/10.5281/zenodo.8250858
- https://doi.org/10.5281/zenodo.8249907

**Article
There are no authors specified! Please add all of them, with appropriate affiliations.**
Authors and affiliation have been added

**Abstract: please use the same structured abstract already developed in the paper. The Abstract section is usually not numbered.**
We used a structured abstract and the section is not numbered anymore (https://doi.org/10.5281/zenodo.8263908)

**Introduction: it should include at least the research questions, and it should also contain, at the very end, how the rest of the paper is actually structured (e.g. "The rest of the paper is structured as follows. In Section 2, ...").**
The introduction section already contained the research questions. Now we specified with RQ1, ...etc.
We added a description of the structure of the paper.

**Materials and Methods: Remove my name as an author of your software - you did it, not me. Cite properly the data you have reused (Meta, COCI, etc.) by creating appropriate bibliographic references for them (pointing to the right version, e.g., on Figshare). Saying "we downloaded Meta" and then adding the link to opencitations.net/meta is not correct.**
Correct citations have been added:
DOAJ. (2023). The DOAJ dataset downloaded 28-05-2023 journalcsv__doaj_20230528_0035_utf8 [Data set]. Zenodo. https://doi.org/10.5281/zenodo.8163248

ERIH PLUS. (2023). ERIH PLUS (EP) dataset "Approved Journals" 27-04-2023. https://doi.org/10.5281/zenodo.8163337

OpenCitations (2022). OpenCitations Meta CSV dataset of all bibliographic metadata. figshare. Dataset. https://doi.org/10.6084/m9.figshare.21747461.v3

**Results: The figures should have a proper caption describing the graph. This should be true for all figures in the whole text.**
All figures have now a caption.

**Discussion: Please identify a subsection here where to list all the limitations properly.**
A subsection of Discussion have been added (4.1. Limitations) 

**Conclusions: they are missing and should also contain some sketches of future works.**
A section 5.Conclusion has been addedd and it contains possible future works.

**References: if you use the references (I agree), please cite them properly in the text without using footnotes, but using APA style.**

We have changed the reference to be APA style, according to guidelines we found [here](https://www.scribbr.com/apa-style/in-text-citation/) the in-text citations have been added as follows:
single author (author, year)
two authors (author & author, year)
more than two authors (author et al., year)
when author is mentioned in the text (year)
general website reference (url)
disambiguation between references with same authors and same years (author, 2023a) (author, 2023b)

**Comment by MaddaGh** [comment]
All issues have been addressed in a final way in the previous comment.

**Comment by essepuntato** [comment]
Fine with me. Thanks for all your revisions!
